apiVersion: v1
kind: Pod
metadata:
  name: nginx-affinity
  labels:
    env: test
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - us-east-1c            
  containers:
  - name: nginx
    image: nginx
 