apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    tier: backend
spec:
  affinity:
    podAntiAffinity:   
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: tier
            operator: In
            values:
            - database
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: nginx
    image: nginx